### ISSUE TITLE
Runtime failure on Win 10

### ISSUE THREAD

**Issue by thinkingcap** [lemonstand/lemonsync#34]
Same error for Python 2 or 3
```
Traceback (most recent call last):
  File "c:\users\davidm\appdata\local\scoop\apps\python\3.6.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\davidm\appdata\local\scoop\apps\python\3.6.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\davidm\AppData\Local\scoop\apps\python\current\scripts\lemonsync.exe\__main__.py", line 5, in <module>
  File "c:\users\davidm\appdata\local\scoop\apps\python\3.6.1\lib\site-packages\lemonsync\LemonSync.py", line 37, in <module>
    from Parser import Parser
ModuleNotFoundError: No module named 'Parser'
```

**Comment by thinkingcap** [comment]
"pip install argparse" didnt help.

**Comment by thinkingcap** [comment]
What worked for me on Win10 x64 using Python 2.7.13
- Clone this git repo
- run python setup.py install
