### ISSUE TITLE
Could not make connection to LemonStand!

### ISSUE THREAD

**Issue by 0devcat0** [lemonstand/lemonsync#36]
Hi, I'm a new user of Lemonsync.

I have installed everything (a few times now) but I am having an issue with my connection when trying to configure it to contact to my store. I get this message:

-----
LemonSync is initiating connection...
Could not make connection to LemonStand!
-----

I've followed all the instructions and checked my lemonstand.cfg file. I'm not sure what to try next. Could anyone point me in the right direction?

Very many thanks!

**Comment by jordantomax** [comment]
I'm having the same problem. I've tried the easy-install option that was suggestions, but still no luck. Please advise, this is a necessity in order to get started using Lemonstand.

**Comment by jordantomax** [comment]
I just tried again using Python3.6.2 and got a new error

```
Traceback (most recent call last):
  File "/Users/jordancooperman/env/lemonstand/bin/lemonsync", line 7, in <module>
    from lemonsync.LemonSync import main
  File "/Users/jordancooperman/env/lemonstand/lib/python3.6/site-packages/lemonsync/LemonSync.py", line 37, in <module>
    from Parser import Parser
ModuleNotFoundError: No module named 'Parser'
```

Are there specific versions of Python that you officially support? Any help or advice would be hugely appreciated. Thanks.

**Comment by jordantomax** [comment]
Still haven't resolved with Python 3.6, but I fell back to python 2 and then realized that my api_host was incorrectly formed and was missing the `//` after `https:`. Now appears to be working.
